### PR TITLE
Homekit Quick Update

### PR DESCRIPTION
**Pull request by wearebono**
Removing code to arm in homekit integration and also quick update in homekit app

### CODE REVIEW

**Review by gjohansson-ST — CHANGES_REQUESTED** [review]
You did not change the code for disarm to allow disarm without code entered.
Would you not change that one too?

**Comment by gjohansson-ST** [comment]
Will close this pr given that I wrote the adjustments slightly different.
Happy though to have more suggestions.
Please try the new beta 0.3.3-beta1 released shortly to test if this works for you

**Comment by wearebono** [comment]
As per Sector Alarm norm, you can't disarm without code, so I did not open that. Your beta also works arming without code. I think it is better to also check property code_arm_required before letting arming without code.

**Comment by wearebono** [comment]
Without return true [https://github.com/gjohansson-ST/sector/pull/25/commits/03ae0e5a456c793b93f7ea027419d0affdbf3a0b] the homekit will not refresh and will wait for the next interval.

**Comment by gjohansson-ST** [comment]
> As per Sector Alarm norm, you can't disarm without code, so I did not open that. Your beta also works arming without code. I think it is better to also check property code_arm_required before letting arming without code.

The intention was to take the code from the config entry if none was supplied but I realized now I forgot to do that.
As we want to allow not entering a code and you take the one from config I believe you need to have false on the code_arm_required property. Do not get why checking the property would change anything as there is no influence on it from somewhere else.

**Comment by gjohansson-ST** [comment]
> Without return true [https://github.com/gjohansson-ST/sector/pull/25/commits/03ae0e5a456c793b93f7ea027419d0affdbf3a0b](url) the homekit will not refresh and will wait for the next interval.

Link not usable for me. Which function do you refer to?

**Comment by wearebono** [comment]
> > Without return true [https://github.com/gjohansson-ST/sector/pull/25/commits/03ae0e5a456c793b93f7ea027419d0affdbf3a0b](url) the homekit will not refresh and will wait for the next interval.
> 
> Link not usable for me. Which function do you refer to?

triggeralarm in init

**Comment by wearebono** [comment]
> > As per Sector Alarm norm, you can't disarm without code, so I did not open that. Your beta also works arming without code. I think it is better to also check property code_arm_required before letting arming without code.
> 
> The intention was to take the code from the config entry if none was supplied but I realized now I forgot to do that.
> As we want to allow not entering a code and you take the one from config I believe you need to have false on the code_arm_required property. Do not get why checking the property would change anything as there is no influence on it from somewhere else.

So if code_arm_required is true, it does not arm without correct code is entered.

**Comment by gjohansson-ST** [comment]
> > > Without return true [https://github.com/gjohansson-ST/sector/pull/25/commits/03ae0e5a456c793b93f7ea027419d0affdbf3a0b](url) the homekit will not refresh and will wait for the next interval.
> > 
> > 
> > Link not usable for me. Which function do you refer to?
> 
> triggeralarm in init
You are absolutely right. Will release new beta shortly to correct this (also)

> > > As per Sector Alarm norm, you can't disarm without code, so I did not open that. Your beta also works arming without code. I think it is better to also check property code_arm_required before letting arming without code.
> > 
> > 
> > The intention was to take the code from the config entry if none was supplied but I realized now I forgot to do that.
> > As we want to allow not entering a code and you take the one from config I believe you need to have false on the code_arm_required property. Do not get why checking the property would change anything as there is no influence on it from somewhere else.
> 
> So if code_arm_required is true, it does not arm without correct code is entered.
Corrent. Could consider to implement it in the config flow so one can choose.

**Comment by gjohansson-ST** [comment]
Have a check on v0.3.3-beta2 released shortly which should now correct it.
Would appreciate if you can test (given that I don't have sector anymore and therefore can not test myself).

**Comment by wearebono** [comment]
> Have a check on v0.3.3-beta2 released shortly which should now correct it.
> Would appreciate if you can test (given that I don't have sector anymore and therefore can not test myself).

Working for me. Great

**Pull request closed without merging**
