### PR TITLE
Use dict.get()

### PR DESCRIPTION
**Pull request by Olen**
Added a few more validations and using dict.get() to avoid exceptions on empty return values.

It is still needed a few more places, I guess:

```
2022-06-12 10:52:21 ERROR (MainThread) [homeassistant.components.lock] Error while setting up sector platform for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/sector/lock.py", line 34, in async_setup_entry
    for lock, lock_data in panel_data["lock"].items():
KeyError: 'lock'
```

### CODE REVIEW

**Comment by einarsi** [comment]
For (increased) completeness, could you include a similar fix for switch as you made for lock?
```Error while setting up sector platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/sector/switch.py", line 34, in async_setup_entry
    for switch, switch_data in panel_data["switch"].items():
KeyError: 'switch'
```

**Comment by gjohansson-ST** [comment]
I am in general not too happy about using .get everywhere to "solve" a data request issue but I guess this makes sense.
I have some other stuff that needs fixing before releasing a new beta so I give it some more time for @Olen to also add in the fix for switch and then we can merge this.

**Comment by Olen** [comment]
> I am in general not too happy about using .get everywhere to "solve" a data request issue but I guess this makes sense.

Well, it depends.  If the API returns different sets of values depending on "something", it is better than just throwing an exception and dying because some attribute is undefined in a dict.
But the return values from the API should also probably be validated further as well.  I just needed something quick and dirty to get up and running.

**Comment by gjohansson-ST** [comment]
> Well, it depends. If the API returns different sets of values depending on "something", it is better than just throwing an exception and dying

I agree so therefore happy to have it as such while it can be figured out.

**Comment by Olen** [comment]
There are probably more places similar checks could be added, but with these at least I don't see any more exceptions here.

**Review by gjohansson-ST — APPROVED** [review]

**Comment by gjohansson-ST** [comment]
Would be happy to get feedback on the last beta now if it works fine or not

**Pull request merged**
