### PR TITLE
fix: 199: Update to new AlarmState enum

### PR DESCRIPTION
**Pull request by sebastian-steinmann**

### CODE REVIEW

**Review by garnser — COMMENTED** [review]
Change seams to work fine, but then I didn't have any issues prior either.

**Comment by sebastian-steinmann** [comment]
This should probl require latest version of HA, not sure where I do that do :D

**Review by gjohansson-ST — CHANGES_REQUESTED** [review]
Change line 75 to `return None` and remove `STATE_UNKNOWN` on line 79.

**Comment by sebastian-steinmann** [comment]
Sorry for half-ass job, I did the change in the online editor, and never saved it seems, thanks for completing it

**Comment by gjohansson-ST** [comment]
> Sorry for half-ass job, I did the change in the online editor, and never saved it seems, thanks for completing it

No worries. Thanks for submitting in the first place!
Always great with contributions!

**Pull request merged**
